name: rake

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  rake:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
        include:
          - ruby: '2.7'
            os: 'ubuntu-latest'
            experimental: true
          - ruby: '2.7'
            os: 'windows-latest'
            experimental: true
          - ruby: '2.7'
            os: 'macos-latest'
            experimental: true
    steps:
      - uses: actions/checkout@master

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Update gems
        run: bundle install --jobs 4 --retry 3

      - name: Install Grpahviz Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install graphviz

      - name: Install Grpahviz macOS
        if: matrix.os == 'macos-latest'
        run: brew install graphviz

      - name: Install Grpahviz Windows
        if: matrix.os == 'windows-latest'
        uses: nick-invision/retry@v1
        with:
          polling_interval_seconds: 5
          timeout_minutes: 5
          max_attempts: 3
          command: choco install --no-progress graphviz

      - name: Check dot command
        if: matrix.os == 'windows-latest'
        run: |
          dot -?

      - name: Run specs
        run: bundle exec rake
